import {cloudRequest} from './cloud.js';
import {questions,dimensions,openQuestions} from './questions.js';
import {makeProfile,encodeProfile,decodeProfile,buildReport,reportText,analysisMaterial} from './core.js';
const $=s=>document.querySelector(s), app=$('#app');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='same-frequency-draft-v1';
let cloudName='',cloudView=0,cloudLoad=0,savedReportText='';
try{cloudName=sessionStorage.getItem('same-frequency-cloud-name')||'';}catch{}
let state={name:'',answers:Array(36).fill(null),texts:Array(4).fill(''),share:false,save:false,index:0},myCode='',profile=null,pairCodes=['',''],pairKind='neutral',report=null,paired=null;
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved?.save===true&&typeof saved.name==='string'&&saved.name.length<=20&&Array.isArray(saved.answers)&&saved.answers.length===36&&saved.answers.every(x=>x===null||Number.isInteger(x)&&x>=0&&x<=3)&&Array.isArray(saved.texts)&&saved.texts.length===4&&saved.texts.every(x=>typeof x==='string'&&x.length<=200)){state={...state,...saved,index:Math.max(0,Math.min(36,Number(saved.index)||0))};}}catch{}
function persist(){try{if(state.save)localStorage.setItem(KEY,JSON.stringify(state));else localStorage.removeItem(KEY);}catch{toast('这台设备无法保存草稿，请在离开前完成并复制答案码。');}}
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4000);}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('已复制');}catch{const d=document.createElement('dialog');const h=document.createElement('h2');h.textContent='请长按或全选复制';const ta=document.createElement('textarea');ta.className='code';ta.value=text;const close=document.createElement('button');close.className='primary';close.textContent='关闭';close.onclick=()=>d.close();d.append(h,ta,close);document.body.append(d);d.addEventListener('close',()=>d.remove());d.showModal();ta.select();}}
function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function go(route){if(location.hash===`#${route}`)render();else location.hash=route;}
function focusHeading(){const h=app.querySelector('h1,h2');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}window.scrollTo({top:0,behavior:'instant'});}
$('#privacy').onclick=()=>$('#info').showModal();
function home(){app.innerHTML=`<div class="home"><div class="hero"><section><div class="eyebrow"><span class="dot"></span> A LITTLE CLOSER · 靠近一点了解</div><h1>你也这样<br><em>想过吗？</em></h1><p class="lead">从一件小事的感受，到心里在意的东西。<br>各自回答，再看看你们的想法在哪里相遇。</p><div class="actions"><a class="primary" href="#quiz">${state.answers.some(x=>x!==null)?'继续我的答卷':'开始我的答卷'} <span>→</span></a><a class="secondary" href="#pair">我有两份答案码</a></div><p class="micro">36 道情境题 · 约 8–12 分钟 · 朋友 / 伴侣都可以<br>不需要知道 MBTI，也没有更好的标准答案。</p></section><div class="art" aria-hidden="true"><div class="orbit"></div><div class="note one"><small>MY LITTLE WORLD</small><div class="circle">我</div><p>那些没说出口的<br>小小想法</p></div><div class="note two"><small>YOUR LITTLE WORLD</small><div class="circle">你</div><p>原来，你的世界<br>是这样的</p></div><span class="art-tag">TWO WORLDS, A CONVERSATION.</span></div></div><div class="home-bottom"><div class="step"><b>01</b><div><h3>先听听自己的答案</h3><p>按真实状态选，不用猜谁会喜欢。</p></div></div><div class="step"><b>02</b><div><h3>交换一份答案码</h3><p>答一次，可以分别配对，也能保存到云端。</p></div></div><div class="step"><b>03</b><div><h3>读懂相似，也聊聊不同</h3><p>一份有答案依据的双人相处报告。</p></div></div></div></div>`;}
function quizSetup(){if(!state.name&&cloudName)state.name=cloudName;app.innerHTML=`<section class="shell"><div class="eyebrow">BEFORE WE BEGIN</div><h1 class="page-title">这一次，按你的心意选。</h1><p class="sub">想一想最近半年的自己。如果两个选项都像你，选更常见的那个。<br>题目偏重感受、想象与价值观，适合喜欢自我探索的人。</p><form id="setup" class="panel"><label class="field">怎么称呼你？<input id="nickname" autocomplete="off" maxlength="20" placeholder="昵称就好" value="${esc(state.name)}" required></label><label class="field">昵称使用方式<select id="nickname-mode"><option value="register">首次使用 · 创建新昵称</option><option value="enter">之前用过 · 进入已有昵称</option></select></label><p class="micro">创建昵称时会联网检查是否重复。这里不验证身份，知道昵称的人可以查看其云端记录；答卷不会自动上传。</p><p class="error" id="nickname-error" role="alert"></p><div id="local-fallback" class="hidden"><p class="notice">暂时无法确认昵称是否重复。可以先用临时昵称答题，完成后保存答案码；这不会创建云端昵称或上传答卷。连接恢复后，再确认唯一昵称并保存配对记录。</p><button type="button" id="continue-local" class="secondary">先用临时昵称答题 →</button></div><label class="check"><input id="save" type="checkbox" ${state.save?'checked':''}><span>在这台设备保存进度。公共设备请不要勾选。</span></label><button class="primary" type="submit">${state.answers.some(x=>x!==null)?'继续答题':'开始答题'} →</button></form><p class="micro">完成后才会生成答案码。小问答可跳过，且由你决定是否分享。<br>这是了解彼此的问卷，不是心理诊断或恋爱匹配量表。</p>${state.answers.some(x=>x!==null)?'<button id="reset" class="text-btn">清除这份草稿，重新开始</button>':''}</section>`;
if(cloudName&&cloudName===state.name)$('#nickname-mode').value='enter';
$('#setup').onsubmit=async e=>{e.preventDefault();const n=$('#nickname').value.trim();if(!n){$('#nickname').setCustomValidity('请填一个昵称');$('#nickname').reportValidity();return;}const button=$('#setup button[type=submit]'),mode=$('#nickname-mode').value,save=$('#save').checked;button.disabled=true;button.textContent='正在确认昵称…';$('#nickname-error').textContent='';$('#local-fallback').classList.add('hidden');try{const result=await cloudRequest(mode,{name:n,consent:true});rememberCloud(result.name);state.name=result.name;state.save=save;persist();if(location.hash==='#quiz'){quizQuestion();focusHeading();}}catch(err){if($('#nickname-error')){$('#nickname-error').textContent=err.message;if(err.status===0||err.status>=500)$('#local-fallback').classList.remove('hidden');button.disabled=false;button.textContent='重试云端连接';}}};$('#continue-local').onclick=()=>{const n=$('#nickname').value.normalize('NFKC').trim();if(!n||n.length>20||/[\p{Cc}\p{Cf}]/u.test(n)){toast('请填写 1～20 个字符的昵称。');return;}state.name=n;state.save=$('#save').checked;persist();quizQuestion();focusHeading();toast('正在使用临时昵称，尚未创建云端记录。');};$('#nickname').oninput=()=>{$('#nickname').setCustomValidity('');$('#local-fallback').classList.add('hidden');};if($('#reset'))$('#reset').onclick=()=>{if(confirm('清除当前草稿？已经复制出去的答案码不会失效。')){state={name:'',answers:Array(36).fill(null),texts:Array(4).fill(''),share:false,save:false,index:0};myCode='';profile=null;persist();quizSetup();}};}
function quizQuestion(){if(state.index===36){openForm();return;}const i=state.index,q=questions[i],answered=state.answers.filter(x=>x!==null).length;app.innerHTML=`<section class="shell"><div class="eyebrow">${esc(dimensions[q.dim].name)} · ${String(q.dim+1).padStart(2,'0')} / 06</div><div class="progress-line"><span>第 ${i+1} 题 / 36</span><span>已回答 ${answered} 题</span></div><div class="progress" role="progressbar" aria-label="答题完成度" aria-valuemin="0" aria-valuemax="36" aria-valuenow="${answered}"><div style="width:${answered/36*100}%"></div></div><form id="question" class="panel"><h1 class="question-title" id="question-title">${esc(q.text)}</h1><div class="options" role="radiogroup" aria-labelledby="question-title">${q.options.map((o,j)=>`<label class="option ${state.answers[i]===j?'selected':''}"><input type="radio" name="answer" value="${j}" ${state.answers[i]===j?'checked':''}><span class="letter">${'ABCD'[j]}</span><span>${esc(o)}</span></label>`).join('')}</div><div class="quiz-actions"><button class="text-btn" type="button" id="prev">${i===0?'← 昵称与保存设置':'← 上一题'}</button><button class="primary" type="submit" id="next" ${state.answers[i]===null?'disabled':''}>${i===35?'继续到小问答':'下一题'} →</button></div></form><p class="micro">选最接近的就好。可以随时返回修改。</p><div class="question-nav" aria-label="跳转题目">${questions.map((_,j)=>`<button type="button" data-q="${j}" aria-label="第 ${j+1} 题${state.answers[j]===null?'，未回答':'，已回答'}" ${j===i?'aria-current="step"':''} class="${state.answers[j]!==null?'answered ':''}${j===i?'current':''}">${j+1}</button>`).join('')}</div></section>`;
app.querySelectorAll('[name=answer]').forEach(el=>el.onchange=()=>{state.answers[i]=Number(el.value);persist();app.querySelectorAll('.option').forEach(l=>l.classList.toggle('selected',l.querySelector('input').checked));$('#next').disabled=false;});$('#question').onsubmit=e=>{e.preventDefault();if(state.answers[i]===null)return;state.index++;persist();quizQuestion();focusHeading();};$('#prev').onclick=()=>{if(i===0)quizSetup();else{state.index--;persist();quizQuestion();}focusHeading();};app.querySelectorAll('[data-q]').forEach(el=>el.onclick=()=>{state.index=+el.dataset.q;persist();quizQuestion();focusHeading();});}
function openForm(){const missing=state.answers.findIndex(x=>x===null);if(missing!==-1){state.index=missing;quizQuestion();toast('还有未答的题，先完成这一题吧。');return;}app.innerHTML=`<section class="shell"><div class="eyebrow">A FEW MORE WORDS · 可跳过</div><h1 class="page-title">选项之外，你还想说什么？</h1><p class="sub">每题最多 200 字。不计分，也不必每题都回答。</p><form id="open-form" class="panel">${openQuestions.map((q,i)=>`<label class="field">${esc(q)}<textarea data-open="${i}" maxlength="200" placeholder="如果愿意，可以写一点……">${esc(state.texts[i])}</textarea></label>`).join('')}<label class="check"><input type="checkbox" id="share" ${state.share?'checked':''}><span>把这四道小问答也放进答案码。我知道收到代码的人能看到这些文字。</span></label><p class="notice">答案码会包含昵称和 36 道选择。它可跨设备读取，不是加密密码；请只分享给你愿意了解你的人。未勾选时，小问答不会进入代码或报告。</p><div id="make-error" class="error" role="alert"></div><div class="quiz-actions"><button type="button" class="text-btn" id="back-questions">← 返回选择题</button><button type="submit" class="primary" id="make-code">生成我的答案码 →</button></div></form></section>`;
app.querySelectorAll('[data-open]').forEach(el=>el.oninput=()=>{state.texts[+el.dataset.open]=el.value;persist();});$('#share').onchange=()=>{state.share=$('#share').checked;persist();};$('#back-questions').onclick=()=>{state.index=35;persist();quizQuestion();focusHeading();};$('#open-form').onsubmit=async e=>{e.preventDefault();const btn=$('#make-code');btn.disabled=true;btn.textContent='正在生成…';try{profile=makeProfile(state.name,state.answers,state.share?state.texts:Array(4).fill(''));myCode=await encodeProfile(profile);go('code');}catch(err){$('#make-error').textContent='生成失败：'+err.message;btn.disabled=false;btn.textContent='重新生成';}};}
function codePage(){if(!myCode){quizSetup();return;}app.innerHTML=`<section class="shell"><div class="eyebrow">YOUR ANSWERS, READY TO SHARE</div><h1 class="page-title">${esc(profile.n)}，你的答卷收好了。</h1><p class="sub">把这份答案码私下发给对方，或者拿到对方的代码后在这里配对。<br>同一份代码可以多次使用，换设备也能读取。</p><div class="panel"><div class="pair-label"><label for="my-code">我的答案码</label><span class="tag">36 / 36 已完成</span></div><textarea readonly id="my-code" class="code" aria-label="我的答案码">${esc(myCode)}</textarea><div class="actions"><button id="copy-code" class="primary">复制答案码</button><button id="save-code" class="secondary">下载保存</button></div><p class="micro">已包含：昵称、36 道选择${profile.t.some(Boolean)?'、你同意分享的小问答':''}。<br>代码完整保存了答案，因此会比普通邀请码长。它不加密，也不能远程撤回。</p></div><div class="actions"><button class="primary" id="use-code">拿两份代码去配对 →</button><button class="secondary" id="edit-code">修改我的答案</button></div><p class="micro">离开前请复制或下载。${state.save?'草稿已在这台设备保存；答案码不会自动云端备份。':'你没有开启草稿保存，刷新页面会丢失当前答卷。'}</p></section>`;$('#copy-code').onclick=()=>copy(myCode);$('#save-code').onclick=()=>download(myCode,'我的答案码.txt');$('#use-code').onclick=()=>{pairCodes[0]=myCode;go('pair');};$('#edit-code').onclick=()=>{go('quiz');};}
function pairPage(){app.innerHTML=`<section class="shell wide"><div class="eyebrow">TWO WORLDS MEET</div><h1 class="page-title">把两份答案，放在一起。</h1><p class="sub">使用对方主动分享给你的代码。报告会展示双方选择，以及各自同意分享的小问答。</p><form id="pair-form"><div class="pair-grid">${[0,1].map(i=>`<div class="panel"><label class="field">${i===0?'第一份答案码':'第二份答案码'}<textarea id="pair-${i}" aria-label="${i===0?'第一份答案码':'第二份答案码'}" placeholder="粘贴 TF1. 开头的完整代码" maxlength="7000" required spellcheck="false">${esc(pairCodes[i])}</textarea></label>${i===0&&myCode?'<button type="button" class="text-btn" id="fill-mine">填入我刚才的答案码</button>':'<span class="micro">完整复制，换行和空格不影响读取。</span>'}</div>`).join('')}</div><label class="field">从什么关系角度读这份报告？<select id="kind"><option value="neutral">不限关系 · 先了解彼此</option><option value="friend">朋友 · 分享与相处</option><option value="partner">伴侣 · 期待与沟通</option></select></label><label class="check"><input type="checkbox" id="consent" required><span>这两份代码由答题者自愿提供，我理解配对后可以看到其中的答案。</span></label><p class="notice">将生成分维度的长报告，通常约 3,000～5,000 字。当前是基于答卷的规则报告，未接入在线 AI；可复制完整分析资料，交给 AI 继续深入解读。</p><p id="pair-error" class="error" role="alert"></p><button type="submit" class="primary" id="generate">生成双人报告 →</button></form><p class="micro">没有答案码？<a class="inline-link" href="#quiz">先完成自己的答卷</a>。生成报告不会自动上传；你可以在报告页选择保存到云端。</p></section>`;$('#kind').value=pairKind;$('#kind').onchange=()=>pairKind=$('#kind').value;[0,1].forEach(i=>$('#pair-'+i).oninput=()=>pairCodes[i]=$('#pair-'+i).value);if($('#fill-mine'))$('#fill-mine').onclick=()=>{$('#pair-0').value=myCode;pairCodes[0]=myCode;};$('#pair-form').onsubmit=async e=>{e.preventDefault();const btn=$('#generate');btn.disabled=true;btn.textContent='正在读取两份答案…';$('#pair-error').textContent='';try{const [a,b]=await Promise.all(pairCodes.map(decodeProfile));if(a.id===b.id)throw new Error('这是同一份答卷。请换成另一个人自愿分享的代码。');paired=[a,b];report=buildReport(a,b,pairKind);savedReportText='';go('report');}catch(err){$('#pair-error').textContent=err.message;btn.disabled=false;btn.textContent='重新生成 →';}};}
function reportPage(){if(!report){pairPage();return;}const r=report,text=savedReportText||reportText(r),count=text.replace(/\s/g,'').length;app.innerHTML=`<article class="shell wide"><header class="report-head"><div class="eyebrow">A CONVERSATION IN ${questions.length} QUESTIONS</div><h1 class="page-title">你们的想法，在这里相遇。</h1><p class="sub">${esc(r.a)} &amp; ${esc(r.b)} · ${{friend:'朋友视角',partner:'伴侣视角',neutral:'不限关系'}[r.kind]}</p><div class="score-row"><div class="score">${r.metrics.score}<span>%</span></div><div class="score-copy">本次选择一致率<br><strong>${r.metrics.same} / 36 道题选择相同</strong><br>描述这份答卷，不预测这段关系。</div></div><span class="tag">答卷规则报告 · 约 ${count.toLocaleString()} 字符</span><div class="dimension-grid">${dimensions.map((d,i)=>`<div class="dimension"><strong>${d.name}</strong><div class="bar"><i style="width:${r.metrics.dimensions[i]/6*100}%"></i></div><small>${r.metrics.dimensions[i]} / 6 题相同</small></div>`).join('')}</div><div class="report-tools"><button class="primary" id="save-cloud-report">保存到云端</button><a class="secondary" href="#cloud">云端记录</a><button class="secondary" id="copy-report">复制报告</button><button class="secondary" id="download-report">下载文字版</button><button class="secondary" id="print-report">打印 / 存为 PDF</button><button class="primary" id="ai-material">复制给 AI 深入分析</button></div><p class="micro">AI 按钮只复制资料，不会自动上传。请自行选择可信的服务，粘贴前可删除不想分享的内容。</p></header><nav class="toc" aria-label="报告目录">${r.sections.map((s,i)=>`<a href="#section-${i}">${s.title}</a>`).join('')}<a href="#ending">读完之后</a></nav><section class="report-section"><h2>先读这一段</h2>${r.intro.map(p=>`<p>${esc(p)}</p>`).join('')}</section>${r.sections.map((s,i)=>`<section class="report-section" id="section-${i}"><div class="eyebrow">0${i+1} / 06</div><h2>${s.title}</h2><p>${esc(s.overview)}</p>${s.items.map(item=>`<h3>${esc(item.title)}</h3><p class="evidence">${esc(item.evidence)}</p><p>${esc(item.body)}</p>`).join('')}<p class="notice">可以聊聊：${esc(s.prompt)}</p></section>`).join('')}${r.shared.length?`<section class="report-section"><h2>选项之外，你们愿意分享的</h2><p class="sub">以下保留原话，不自动解释隐藏含义。未分享不代表对方没有想法。</p>${r.shared.map(x=>`<h3>${esc(x.q)}</h3><p class="open-answer">${esc(r.a)}：${esc(x.a||'未分享')}\n\n${esc(r.b)}：${esc(x.b||'未分享')}</p>`).join('')}</section>`:''}<details><summary>查看全部 36 题的答案对照</summary>${questions.map(q=>`<h3>${q.id}. ${esc(q.text)}</h3><p class="evidence">${esc(r.a)}：${esc(q.options[+paired[0].a[q.id-1]])}<br>${esc(r.b)}：${esc(q.options[+paired[1].a[q.id-1]])}</p>`).join('')}</details><section class="report-section" id="ending"><h2>读完之后，留一点时间给彼此。</h2>${r.ending.map(p=>`<p>${esc(p)}</p>`).join('')}</section><div class="actions no-print"><a class="secondary" href="#pair">用其他答卷配对</a><a class="secondary" href="#home">返回首页</a></div></article>`;
$('#save-cloud-report').onclick=saveCloudDialog;$('#copy-report').onclick=()=>copy(text);$('#download-report').onclick=()=>download(text,'双人相处报告.txt');$('#print-report').onclick=()=>window.print();$('#ai-material').onclick=()=>copy(analysisMaterial(...paired,pairKind));}
function render(){cloudView++;const hash=location.hash.slice(1)||'home';if(hash.startsWith('section-')||hash==='ending'){if(!report){go('pair');return;}if(!document.getElementById(hash))reportPage();document.getElementById(hash)?.scrollIntoView({behavior:'instant'});return;}if(hash==='quiz')quizSetup();else if(hash==='code')codePage();else if(hash==='pair')pairPage();else if(hash==='report')reportPage();else if(hash==='cloud')cloudPage();else home();focusHeading();}
function rememberCloud(name){cloudName=name;try{sessionStorage.setItem('same-frequency-cloud-name',name);}catch{}}
function cloudPage(){
 const requestId=++cloudView;
 app.innerHTML=`<section class="shell wide"><div class="eyebrow">SAVED TOGETHER · 云端记录</div><h1 class="page-title">用昵称，找回你们的记录。</h1><p class="sub">无需密码。输入已有昵称可查看；第一次使用可以创建一个不重复的昵称。</p><p class="notice">这里不验证身份，知道昵称的人都能查看对应的配对答案与报告。请只保存双方同意按昵称可见的内容。</p><form class="panel" id="cloud-entry"><label class="field">昵称<input id="cloud-name" maxlength="20" required autocomplete="off" value="${esc(cloudName||state.name)}" placeholder="输入答题时的昵称"></label><div class="actions"><button class="primary" type="submit" id="cloud-enter">进入已有昵称 →</button><button class="secondary" type="button" id="cloud-create">创建新昵称</button></div><p id="cloud-error" class="error" role="alert"></p></form><div id="cloud-list" aria-live="polite"></div></section>`;
 async function enter(action){const name=$('#cloud-name').value.trim();if(!name){$('#cloud-name').reportValidity();return;}const field=$('#cloud-error');$('#cloud-enter').disabled=true;$('#cloud-create').disabled=true;field.textContent='';try{const result=await cloudRequest(action,{name,consent:true});rememberCloud(result.name);if(requestId!==cloudView||location.hash!=='#cloud')return;$('#cloud-name').value=result.name;await loadCloudRecords(requestId);}catch(e){if(requestId===cloudView&&$('#cloud-error'))field.textContent=e.message;}finally{if(requestId===cloudView&&$('#cloud-enter')){$('#cloud-enter').disabled=false;$('#cloud-create').disabled=false;}}}
 $('#cloud-entry').onsubmit=e=>{e.preventDefault();enter('enter');};$('#cloud-create').onclick=()=>enter('register');
 if(cloudName)loadCloudRecords(requestId);
}
async function loadCloudRecords(requestId){
 const loadId=++cloudLoad;
 const list=$('#cloud-list');if(!list)return;list.innerHTML='<p class="sub">正在读取云端记录…</p>';
 try{const result=await cloudRequest('list',{name:cloudName});if(loadId!==cloudLoad||requestId!==cloudView||location.hash!=='#cloud')return;
 list.innerHTML=`<div class="pair-label"><h2 class="page-title" style="font-size:24px">${esc(result.name)}的配对记录</h2><span class="tag">${result.records.length} / 100 份</span></div>${result.records.length?result.records.map(r=>`<article class="record-card"><div><h3>${esc(r.title)}</h3><p class="micro">${esc(new Date(r.created_at).toLocaleString('zh-CN'))} · ${{friend:'朋友',partner:'伴侣',neutral:'不限关系'}[r.kind]||'不限关系'} · ${Number(r.score)}% 选择相同</p></div><button class="secondary" data-record="${esc(r.id)}">查看报告 →</button></article>`).join(''):'<div class="panel"><p>这个昵称还没有保存的配对记录。</p><p class="sub">先用两份答案码生成报告，再点击“保存到云端”。</p><a class="primary" href="#pair">去配对 →</a></div>'}<p class="micro">这些记录保存在云端；换设备后，输入同一个昵称即可找回。再次保存相同答卷和关系视角不会重复添加。</p>`;
 list.querySelectorAll('[data-record]').forEach(button=>button.onclick=async()=>{button.disabled=true;button.textContent='正在打开…';try{const saved=await cloudRequest('record',{name:cloudName,id:button.dataset.record});const profiles=await Promise.all(saved.codes.map(decodeProfile));if(requestId!==cloudView||location.hash!=='#cloud')return;paired=profiles;pairCodes=saved.codes;pairKind=saved.kind;report=saved.report;savedReportText=saved.reportText;go('report');}catch(e){toast(e.message);button.disabled=false;button.textContent='查看报告 →';}});
 }catch(e){if(loadId===cloudLoad&&requestId===cloudView&&location.hash==='#cloud'){list.innerHTML=`<p class="error">${esc(e.message)}</p><button class="secondary" id="retry-cloud">重新读取</button>`;$('#retry-cloud').onclick=()=>loadCloudRecords(requestId);}}
}
function saveCloudDialog(){
 if(!paired||!report)return;
 const d=document.createElement('dialog');d.innerHTML=`<h2>保存这份配对报告</h2><form id="cloud-save-form"><label class="field">保存到哪个昵称？<select id="save-owner">${[...new Set(paired.map(p=>p.n))].map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('')}</select></label><p class="sub">昵称不存在时会创建；已经存在时，加入这个昵称的记录。保存两份答卷、关系视角及这份报告。</p><label class="check"><input id="cloud-save-consent" type="checkbox" required><span>双方已知晓并同意：任何知道这个昵称的人都能查看这些答案与报告。</span></label><p class="error" id="cloud-save-error" role="alert"></p><div class="actions"><button class="primary" type="submit" id="cloud-save-submit">确认保存</button><button class="secondary" type="button" id="cloud-save-cancel">取消</button></div></form>`;document.body.append(d);d.addEventListener('close',()=>d.remove());d.showModal();const select=d.querySelector('#save-owner');if(paired.some(p=>p.n===cloudName))select.value=cloudName;
 const codes=[...pairCodes],kind=pairKind;
 d.querySelector('#cloud-save-cancel').onclick=()=>d.close();d.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=d.querySelector('#cloud-save-submit');button.disabled=true;button.textContent='正在保存…';d.querySelector('#cloud-save-error').textContent='';try{let result;const name=select.value;try{result=await cloudRequest('enter',{name});}catch(err){if(err.status!==404)throw err;try{result=await cloudRequest('register',{name,consent:true});}catch(r){if(r.status!==409)throw r;result=await cloudRequest('enter',{name});}}
 const saved=await cloudRequest('save',{name:result.name,codes,kind,consent:true});rememberCloud(result.name);d.close();toast(saved.duplicate?'这份报告已经保存过，可在云端记录查看。':'已保存到云端，换设备也能找回。');
 }catch(err){if(d.isConnected){d.querySelector('#cloud-save-error').textContent=err.message;button.disabled=false;button.textContent='重试保存';}}};
}

window.addEventListener('hashchange',render);render();
