import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {handleCloud,normalizeName} from '../server/cloud.js';
import {makeProfile,encodeProfile} from '../server/shared/core.js';
function database(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('../drizzle/0000_fuzzy_sunset_bain.sql',import.meta.url),'utf8'));return {sql,prepare(query){let args=[];return{bind(...values){args=values;return this;},async first(){return sql.prepare(query).get(...args)||null;},async all(){return{results:sql.prepare(query).all(...args)};},async run(){return sql.prepare(query).run(...args);}};}};}
async function request(db,action,body,origin='https://dev-yaojiabei.github.io'){const res=await handleCloud(new Request(`https://same-frequency-records.yaoshiyou.chatgpt.site/api/cloud/${action}`,{method:'POST',headers:{'Content-Type':'application/json','Origin':origin},body:JSON.stringify(body)}),{DB:db});return {status:res.status,body:await res.json(),headers:res.headers};}
const pair=async()=>Promise.all([makeProfile('测试甲',Array(36).fill(0),Array(4).fill('')),makeProfile('测试乙',Array(36).fill(1),Array(4).fill(''))].map(encodeProfile));
test('canonical nickname identity handles full-width, case and spaces',()=>{assert.equal(normalizeName('  ＡＢＣ  ').key,'abc');assert.throws(()=>normalizeName('x\u200by'));assert.throws(()=>normalizeName(' '.repeat(20)));});
test('atomic registration rejects equivalent duplicates, existing nickname remains accessible',async()=>{const db=database();let r=await request(db,'register',{name:'AbC',consent:true});assert.equal(r.status,201);r=await request(db,'register',{name:' ＡＢＣ ',consent:true});assert.equal(r.status,409);r=await request(db,'enter',{name:'abc'});assert.equal(r.body.name,'AbC');assert.equal((await request(db,'enter',{name:'不存在'})).status,404);});
test('save, durable reload, duplicate idempotency and nickname-scoped reads',async()=>{const db=database(),codes=await pair();await request(db,'register',{name:'测试甲',consent:true});await request(db,'register',{name:'测试乙',consent:true});const first=await request(db,'save',{name:'测试甲',codes,kind:'partner',consent:true});assert.equal(first.status,201);const again=await request(db,'save',{name:'测试甲',codes:[...codes].reverse(),kind:'partner',consent:true});assert.equal(again.body.duplicate,true);const list=await request(db,'list',{name:'测试甲'});assert.equal(list.body.records.length,1);const got=await request(db,'record',{name:'测试甲',id:first.body.id});assert.deepEqual(got.body.codes,codes);assert.ok(got.body.reportText.length>3000);assert.equal((await request(db,'record',{name:'测试乙',id:first.body.id})).status,404);assert.equal((await request(db,'list',{name:'测试乙'})).body.records.length,0);});
test('rejects unconsented uploads, foreign origins, bad codes and unrelated nickname',async()=>{const db=database(),codes=await pair();assert.equal((await request(db,'register',{name:'test'})).status,400);assert.equal((await request(db,'register',{name:'test',consent:true},'https://example.org')).status,403);await request(db,'register',{name:'其他人',consent:true});assert.equal((await request(db,'save',{name:'其他人',codes,kind:'friend',consent:true})).status,400);assert.equal((await request(db,'save',{name:'其他人',codes:['bad','bad'],kind:'friend',consent:true})).status,400);assert.equal((await request(db,'save',{name:'其他人',codes,kind:'friend'})).status,400);});
test('CORS preflight and body limits',async()=>{const r=await handleCloud(new Request('https://same-frequency-records.yaoshiyou.chatgpt.site/api/cloud/list',{method:'OPTIONS',headers:{Origin:'https://dev-yaojiabei.github.io'}}),{});assert.equal(r.status,204);assert.equal(r.headers.get('Access-Control-Allow-Origin'),'https://dev-yaojiabei.github.io');const bad=await request(database(),'enter',{name:'a'.repeat(25000)});assert.equal(bad.status,413);});
